# Generated by Django 5.2.8 on 2025-11-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
