# Generated by Django 5.2.8 on 2025-11-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_studentprofile_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, unique=True),
        ),
    ]
