# Generated by Django 5.2.8 on 2025-11-26 13:01

import exams.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(blank=True, null=True, validators=[exams.validators.validate_not_past_exam]),
        ),
    ]
