# Generated by Django 5.2.8 on 2025-11-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0003_alter_studentprofile_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='roll_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('roll_number__isnull', False)), fields=('class_level', 'academic_year', 'roll_number'), name='unique_roll_per_class_year'),
        ),
    ]
