# Generated by Django 5.2.8 on 2025-11-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_studentenrollment_roll_number_and_more'),
        ('accounts', '0004_studentprofile_student_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='teacherassignment',
            constraint=models.UniqueConstraint(fields=('class_level', 'subject', 'academic_year'), name='unique_class_subject_year_assignment'),
        ),
    ]
